language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jas1217/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jas1217/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-453546859657"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY